[package]
name = "depo_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
reqwest = { version = "0.12", features = ["json"] }
git2 = "0.20.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
semver = "1.0"
dotenv = "0.15"
tempfile = "3.23.0"
